name: Terraform CI

on: 
  push:
    branches:
    branches: [ "feature-603/create-repo-creation-approval-github-action-workflow" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - name: Check out code  
      uses: actions/checkout@v3
      with:
        -ref: 

    - name: Run a Terraform Format 
      uses: docker://hashicorp/terraform:1.2.4
      with:
        entrypoint: terraform
        args: fmt

    - name: Run a Terraform init  
      uses: docker://hashicorp/terraform:1.2.4
      with:
        entrypoint: terraform
        args: init

    - name: Run a Terraform validate    
      uses: docker://hashicorp/terraform:1.2.4
      with:
        entrypoint: terraform
        args: validate